In [43]:
import pandas as pd

df = pd.read_csv('proteins_under_100.csv')
#df = pd.read_csv('proteins_many.csv')

df.head()

,Unnamed: 0,names,sequences,length,chains,helices,sheets
0,0,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb200d.ent,"['DT', 'DA', 'DA', 'DC', 'DC', 'DC', 'DT', 'DA...",12,2,0,0
1,1,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb300d.ent,"['G', 'U', 'G', 'G', 'U', 'C', 'U', 'G', 'A', ...",47,2,0,0
2,2,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb400d.ent,"['5CM', 'DG', 'DG', 'DC', '5CM', 'DG', '5CM', ...",12,2,0,0
3,3,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb100d.ent,"['C', 'DC', 'DG', 'DG', 'DC', 'DG', 'DC', 'DC'...",21,2,0,0
4,4,/Volumes/UCG Hard D./PDB Files/pdb/01/pdb101d.ent,"['DC', 'DG', 'DC', 'DG', 'DA', 'DA', 'DT', 'DT...",26,2,0,0

In [44]:
# d3to1 = {'CYS': 'C', 'ASP': 'D', 'SER': 'S', 'GLN': 'Q', 'LYS': 'K',
# 'ILE': 'I', 'PRO': 'P', 'THR': 'T', 'PHE': 'F', 'ASN': 'N', 
# 'GLY': 'G', 'HIS': 'H', 'LEU': 'L', 'ARG': 'R', 'TRP': 'W', 
# 'ALA': 'A', 'VAL':'V', 'GLU': 'E', 'TYR': 'Y', 'MET': 'M'}

# for i in d3to1:
#     proteins.append(i)

def get_natural_proteins(df):
    acids = ['CYS', 'ASP', 'SER', 'GLN', 'LYS', 'ILE', 'PRO', 'THR', 'PHE', 'ASN', 'GLY', 'HIS', 'LEU', 'ARG', 'TRP', 'ALA', 'VAL', 'GLU', 'TYR', 'MET']

    sequences = []
    index = []
    counter = 0

    for sequence in df.sequences:
        sequence = sequence.replace("'", "")
        sequence = sequence.replace(" ", "")
        sequence = sequence.replace("[", "")
        sequence = sequence.replace("]", "")
        sequence = sequence.split(",")
        for acid in sequence:
            if acid not in acids:
                break
        else:
            sequences.append(sequence)
            index.append(counter)
        counter += 1
    
    return sequences, index


natural = get_natural_proteins(df)

sequences = natural[0]
indices = natural[1]

#indices[-1]

#print(sequences[4])
#print(df.sequences[372]) # it works

In [46]:
natural_proteins = df.loc[indices]
natural_proteins.drop("Unnamed: 0", axis=1, inplace=True)
natural_proteins.to_csv("natural_proteins_under_100.csv")   # create csv

In [47]:
natural_proteins = pd.read_csv("natural_proteins_under_100.csv")  # read csv
natural_proteins.head()

,Unnamed: 0,names,sequences,length,chains,helices,sheets
0,355,/Volumes/UCG Hard D./PDB Files/pdb/a1/pdb1a1u.ent,"['GLU', 'TYR', 'PHE', 'THR', 'LEU', 'GLN', 'IL...",58,2,2,2
1,356,/Volumes/UCG Hard D./PDB Files/pdb/a1/pdb1a1w.ent,"['MET', 'ASP', 'PRO', 'PHE', 'LEU', 'VAL', 'LE...",83,1,6,0
2,357,/Volumes/UCG Hard D./PDB Files/pdb/a1/pdb1a1z.ent,"['MET', 'ASP', 'PRO', 'PHE', 'LEU', 'VAL', 'LE...",83,1,5,0
3,371,/Volumes/UCG Hard D./PDB Files/pdb/a2/pdb7a2r.ent,"['GLY', 'GLY', 'VAL', 'THR', 'LEU', 'PHE', 'VA...",61,1,0,5
4,372,/Volumes/UCG Hard D./PDB Files/pdb/a2/pdb7a2s.ent,"['GLY', 'GLY', 'VAL', 'THR', 'LEU', 'PHE', 'VA...",60,1,0,5