In [1]:
import pandas as pd

df = pd.read_csv("Data/many_proteins.csv")

df.head()

,Unnamed: 0,names,sequences,length,chains,helices,sheets
0,0,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb200d.ent,"['DT', 'DA', 'DA', 'DC', 'DC', 'DC', 'DT', 'DA...",12,2,0,0
1,1,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb200l.ent,"['MET', 'ASN', 'ILE', 'PHE', 'GLU', 'MET', 'LE...",166,1,11,2
2,2,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb300d.ent,"['G', 'U', 'G', 'G', 'U', 'C', 'U', 'G', 'A', ...",47,2,0,0
3,3,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb400d.ent,"['5CM', 'DG', 'DG', 'DC', '5CM', 'DG', '5CM', ...",12,2,0,0
4,4,/Volumes/UCG Hard D./PDB Files/pdb/00/pdb100d.ent,"['C', 'DC', 'DG', 'DG', 'DC', 'DG', 'DC', 'DC'...",21,2,0,0

In [9]:
d3to1 = {'CYS': 'C', 'ASP': 'D', 'SER': 'S', 'GLN': 'Q', 'LYS': 'K',
 'ILE': 'I', 'PRO': 'P', 'THR': 'T', 'PHE': 'F', 'ASN': 'N', 
 'GLY': 'G', 'HIS': 'H', 'LEU': 'L', 'ARG': 'R', 'TRP': 'W', 
 'ALA': 'A', 'VAL':'V', 'GLU': 'E', 'TYR': 'Y', 'MET': 'M'}

sequences_list = []
translated_seq= ""
    
for sequence in df.sequences:
    sequence = sequence.replace("'", "")
    sequence = sequence.replace(" ", "")
    sequence = sequence.replace("[", "")
    sequence = sequence.replace("]", "")
    sequence = sequence.split(",")
    
    for j in sequence:
        translated_seq = translated_seq + d3to1[j]
        
    sequences_list.append(translated_seq)
    translated_seq= ""

In [10]:
df.drop("sequences", axis=1, inplace=True)
df.drop("original index", axis=1, inplace=True)
sequences = pd.DataFrame({'sequences': sequences_list})
df = pd.concat([df, sequences], axis=1)

df.to_csv("natural_seq.csv", index=False)

df.head()

,names,length,chains,helices,sheets,sequences
0,/Volumes/UCG Hard D./PDB Files/pdb/04/pdb104l.ent,328,2,22,6,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSAA...
1,/Volumes/UCG Hard D./PDB Files/pdb/08/pdb208l.ent,131,1,9,5,KVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGYNTRATNYN...
2,/Volumes/UCG Hard D./PDB Files/pdb/09/pdb209l.ent,165,1,8,2,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
3,/Volumes/UCG Hard D./PDB Files/pdb/13/pdb213l.ent,163,1,9,2,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...
4,/Volumes/UCG Hard D./PDB Files/pdb/14/pdb214l.ent,163,1,9,2,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...

In [75]:
# This code counts the incidence of each amino acid in each sequence and adds them to a list

df = pd.read_csv("natural_100_seq.csv")    

letters = ['C', 'D', 'S', 'Q', 'K', 'I', 'P', 'T', 'F', 'N', 'G', 'H', 'L', 'R', 'W', 'A', 'V', 'E', 'Y', 'M']
counts = {}

for i in letters:
    counts[i] = 0
    
C = []
D = []
S = []
Q = []
K = []
I = []
P = []
T = []
F = []
N = []
G = []
H = []
L = []
R = []
W = []
A = []
V = []
E = []
Y = []
M = []

#limit = 0
    
for sequence in df.sequences:
    #if limit == 50:
    #    break
    
    for letter in letters: # reset counts for each letter
        counts[letter] = 0

    #print("before", counts["C"])
        
    for acid in sequence:  # check for each acid in the sequence
        for letter in letters:
            if acid == letter:
                counts[letter] += 1

    #print("after", counts["C"])
    C.append(counts["C"])
    D.append(counts["D"])
    S.append(counts["S"])
    Q.append(counts["Q"])
    K.append(counts["K"])
    I.append(counts["I"])
    P.append(counts["P"])
    T.append(counts["T"])
    F.append(counts["F"])
    N.append(counts["N"])
    G.append(counts["G"])
    H.append(counts["H"])
    L.append(counts["L"])
    R.append(counts["R"])
    W.append(counts["W"])
    A.append(counts["A"])
    V.append(counts["V"])
    E.append(counts["E"])
    Y.append(counts["Y"])
    M.append(counts["M"])
    
    #limit += 1

In [84]:
df = pd.read_csv("natural_100_seq.csv")

zipped = list(zip(C, D, S, Q, K, I, P, T, F, N, G, H, L, R, W, A, V, E, Y, M))
counts = pd.DataFrame(zipped, columns=["C", "D", "S", "Q", "K", "I", "P", "T", "F", "N", "G", "H", "L", "R", "W", "A", "V", "E", "Y", "M"])

df = pd.concat([df, counts], axis=1)
df.head()

,names,length,chains,helices,sheets,sequences,C,D,S,Q,...,G,H,L,R,W,A,V,E,Y,M
0,/Volumes/UCG Hard D./PDB Files/pdb/a1/pdb1a1u.ent,58,2,2,2,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,0,2,0,4,...,2,0,6,8,0,4,0,12,4,0
1,/Volumes/UCG Hard D./PDB Files/pdb/a1/pdb1a1w.ent,83,1,6,0,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,1,8,10,6,...,6,3,27,16,0,5,5,20,5,2
2,/Volumes/UCG Hard D./PDB Files/pdb/a1/pdb1a1z.ent,83,1,5,0,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2,14,20,8,...,11,6,48,24,0,6,10,28,5,4
3,/Volumes/UCG Hard D./PDB Files/pdb/a2/pdb7a2r.ent,61,1,0,5,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2,19,23,9,...,17,8,53,25,2,10,15,33,9,4
4,/Volumes/UCG Hard D./PDB Files/pdb/a2/pdb7a2s.ent,60,1,0,5,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2,23,26,10,...,23,10,58,26,4,14,20,38,13,4

In [85]:
df.to_csv("natural_100_seq_feat.csv", index=False)

In [89]:
df = pd.read_csv("Data/natural_100_seq_feat.csv")
df.tail()

,names,length,chains,helices,sheets,sequences,C,D,S,Q,...,G,H,L,R,W,A,V,E,Y,M
1146,/Volumes/UCG Hard D./PDB Files/pdb/r7/pdb1r7j.ent,90,1,4,2,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2102,3833,4190,3191,...,5238,1359,6795,4177,1055,5235,5382,5591,2662,1479
1147,/Volumes/UCG Hard D./PDB Files/pdb/ra/pdb3ra6.ent,99,1,5,4,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2102,3838,4195,3193,...,5249,1360,6804,4184,1055,5248,5390,5597,2666,1482
1148,/Volumes/UCG Hard D./PDB Files/pdb/ra/pdb4rah.ent,99,1,0,12,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2105,3845,4203,3196,...,5252,1364,6811,4189,1057,5250,5397,5605,2672,1483
1149,/Volumes/UCG Hard D./PDB Files/pdb/rb/pdb1rb4.ent,91,3,3,0,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2105,3848,4206,3199,...,5253,1367,6829,4195,1057,5256,5405,5621,2675,1486
1150,/Volumes/UCG Hard D./PDB Files/pdb/rb/pdb2rb8.ent,93,1,0,11,EYFTLQIRGRERFEKIREYNEALELKDAQEYFTLQIRGRERFEKIR...,2105,3858,4213,3202,...,5259,1367,6836,4199,1058,5259,5410,5628,2678,1489